include:
  # TOTEM
  - board: xiao_ble
    shield: totem_left
  - board: xiao_ble
    shield: totem_right
  # Ferris Sweep
  - board: nice_nano
    shield: cradio_left
  - board: nice_nano
    shield: cradio_right
  # ZilpZalp
  - board: xiao_ble
    shield: zilpzalp_ble
